name: edu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - catboost
  - statsmodels
  - beautifulsoup4
  - jupyterlab
  - ipywidgets
  - tqdm
  - plotly
  - openpyxl
  - xlsxwriter
  - kaggle
  - pip
  - pip:
      - lightning-utilities
      - pytorch-ignite
      - scipy
      - torchmetrics
      - torchsummary
      - opendatasets
